# SPDX-FileCopyrightText: © 2026 DSLab - Fondazione Bruno Kessler
#
# SPDX-License-Identifier: Apache-2.0

input:
  kind: "mjpeg"
  spec:
    url: "http://go2rtc:1984/api/stream.mjpeg?src=example"
    frame_interval: 10    
    read_timeout: 10

output:
  kind: "stdout"
  spec: {}

flow:
  type: "sequence"
  name: "vqa-pipeline"
  nodes:
    - type: "service"
      name: "anon-service"
      config:
        kind: "openinference"
        spec:
          address: "anonymization:9000"
          model_name: "haar_face_cascade"
          num_instances: 4  
          timeout: 10      

          input_tensor_spec:
            - name: "image"
              datatype: "UINT8"
              shape: [-1, -1]
          
          output_tensor_spec:
            - name: "image"
              datatype: "UINT8"
              shape: [-1, -1]
                    
          output_template: |
            {{. | jp "$.outputs[0].data" | json }}
    - type: "service"
      name: "blip-vqa-service"
      config:
        kind: "openinference"
        spec:
          address: "vqa:9000"
          model_name: "vqa_blip"
          num_instances: 4  
          timeout: 10      

          input_tensor_spec:
            - name: "image"
              datatype: "UINT8"
              shape: [-1, -1]
          
          output_tensor_spec:
            - name: "caption"
              datatype: "BYTES"
              shape: [-1, -1]
          
          input_templates:
            - name: "image"
              template: |
                {{ . }}
          output_template: |
            {
              "caption": {{. | jp "$.outputs[0].data" }},
            }